// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvmBH7Ua5sejUvKNav2XRI2_annUAC0w',
    appId: '1:292140886502:web:7afe337d204bf046e0ce27',
    messagingSenderId: '292140886502',
    projectId: 'simple-chat-app-11ece',
    authDomain: 'simple-chat-app-11ece.firebaseapp.com',
    storageBucket: 'simple-chat-app-11ece.appspot.com',
    measurementId: 'G-5V0PQQK7S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6T8so3KON2y_HZS0yGveAZ0sjnUL7j4',
    appId: '1:292140886502:android:fa0e825c344309f9e0ce27',
    messagingSenderId: '292140886502',
    projectId: 'simple-chat-app-11ece',
    storageBucket: 'simple-chat-app-11ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgFeEaX4cSrdBH-wudJdwiJdjfOauhqJM',
    appId: '1:292140886502:ios:b710a45d6341c2cbe0ce27',
    messagingSenderId: '292140886502',
    projectId: 'simple-chat-app-11ece',
    storageBucket: 'simple-chat-app-11ece.appspot.com',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgFeEaX4cSrdBH-wudJdwiJdjfOauhqJM',
    appId: '1:292140886502:ios:b710a45d6341c2cbe0ce27',
    messagingSenderId: '292140886502',
    projectId: 'simple-chat-app-11ece',
    storageBucket: 'simple-chat-app-11ece.appspot.com',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdvmBH7Ua5sejUvKNav2XRI2_annUAC0w',
    appId: '1:292140886502:web:388f538ac78a4b0fe0ce27',
    messagingSenderId: '292140886502',
    projectId: 'simple-chat-app-11ece',
    authDomain: 'simple-chat-app-11ece.firebaseapp.com',
    storageBucket: 'simple-chat-app-11ece.appspot.com',
    measurementId: 'G-QN3F8C487Y',
  );
}
